using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;

namespace LoggingUtils
{
    internal class CorrelationMiddleware
    {
        private readonly RequestDelegate _next;

        public CorrelationMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public Task Invoke(HttpContext context)
        {
            context.Request.Headers.TryGetValue("x-request-id", out var value); // header value of type UUID generated by Envoy
            var correlationId = value.FirstOrDefault() ?? Guid.NewGuid().ToString();
            using (Correlator.BeginCorrelationScope(correlationId))
            {
                return _next.Invoke(context);
            }
        }
    }

    public static class CorrelationEx
    {
        public static IApplicationBuilder UseCorrelation(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<CorrelationMiddleware>();
        }
    }
}
